baseURL: "https://jedipunkz.github.io"
title: "jedipunkz ğŸš€ ã®ãƒ–ãƒ­ã‚°"
pagination:
  pagerSize: 8
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

# GA4 Measurement ID
googleAnalytics: "G-2H91XCYVZ8"

minify:
  disableXML: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: About Me
          url: about
          weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  canonifyURLs: true
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Theme PaperMod
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  displayFullLangName: true
  assets:
    favicon: '/favicon.ico'
    favicon16x16: '/favicon-16x16.png'
    favicon32x32: '/favicon-32x32.png'
    apple_touch_icon: '/apple-touch-icon.png'
  images: ["jedipunkz.jpg"]
  cover:
    image: "jedipunkz.jpg"

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "https://jedipunkz.github.io/jedipunkz.jpg"
    imageTitle: jedipunkz
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "jedipunkz ğŸš€ ã®ãƒ–ãƒ­ã‚°"
    Content: >
      SRE ã«ãªã‚‹ãŸã‚ã«å­¦ã‚“ã§ã‚†ããƒ–ãƒ­ã‚°ã§ã™
  socialIcons:
    - name: twitter
      url: "http://x.com/jedipunkz"
    - name: github
      url: "https://github.com/jedipunkz"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: true
    simple: true

  x:
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true

markup:
  goldmark:
    renderer:
      unsafe: true
