baseURL: "https://jedipunkz.github.io"
title: "jedipunkz ğŸš€ ã®ãƒ–ãƒ­ã‚°"
pagination:
  pagerSize: 8
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
# services:
#   googleAnalytics:
#     id: UA-30563095-1
googleAnalytics: "UA-30563095-1"

minify:
  disableXML: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: About Me
          url: about
          weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Theme PaperMod
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  displayFullLangName: true
  assets:
    favicon: './pix/jedipunkz.jpg'
  images: ["jedipunkz.jpg"]
  cover:
    image: "jedipunkz.jpg"

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "https://jedipunkz.github.io/jedipunkz.jpg"
    imageTitle: jedipunkz
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "jedipunkz ğŸš€ ã§ã™ ğŸ‘‹"
    Content: >
      ã‚¤ãƒ³ãƒ•ãƒ©ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã‹ã‚‰ SRE ã¸ã®è»¢èº«ãƒ–ãƒ­ã‚°
  socialIcons:
    - name: twitter
      url: "http://twitter.com/jedipunkz"
    - name: github
      url: "https://github.com/jedipunkz"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: true
    simple: true

  x:
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true

markup:
  goldmark:
    renderer:
      unsafe: true
